modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="minebound"
version="${file.jarVersion}"
displayName="MineBound"
logoFile=""
credits="Thanks for MineBound goes to the MineBoundTeam"
authors="MineBound Team"
description='''
MineBound is a cross-disciplinary Minecraft mod with a primary focus on unique, fast-paced, real-time magic using a secondary configurable spell inventory and key binds. 

Spells can be combined through equipping either in the primary, secondary, or tertiary (configurable) slot, where each slot dictates use, either for active attacking/battle or passive defensive/utility capabilities. The gameplay loop of the mod will primarily consist of researching and crafting new spells, and strategically equipping them to get to the next tier of casting. 

Many of these mods utilize spell books or require active usage of one spell at a time. With MineBound we are attempting to allow users to create unique spell combinations through choice equipment instead of items which is the preferred method for most magic mods.
'''

[[dependencies.minebound]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.minebound]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"