modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="minebound"
version="${file.jarVersion}"
displayName="MineBound"
logoFile=""
credits="Thanks for MineBound goes to the MineBoundTeam"
authors="MineBoundTeam"
description='''
We add magic to minecraft.
'''

[[dependencies.minebound]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.minebound]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"